// <auto-generated />
using System;
using AirportApp.ClassLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportApp.ClassLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddOnFlightTicket", b =>
                {
                    b.Property<int>("SelectedAddOnsId")
                        .HasColumnType("int");

                    b.Property<int>("TicketsId")
                        .HasColumnType("int");

                    b.HasKey("SelectedAddOnsId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("FlightTicket_AddOns", (string)null);
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AddOn_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BasePrice")
                        .HasColumnType("real")
                        .HasColumnName("Base_Price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 40f,
                            Name = "Extra 20kg Bag"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 15f,
                            Name = "Priority Boarding"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 12f,
                            Name = "In-flight Meal"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 10f,
                            Name = "Fast Track Security"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 35f,
                            Name = "Lounge Access"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Airport_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Airport_Code");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportCode = "LHR",
                            City = "London",
                            Name = "London Heathrow"
                        },
                        new
                        {
                            Id = 2,
                            AirportCode = "JFK",
                            City = "New York",
                            Name = "John F. Kennedy"
                        },
                        new
                        {
                            Id = 3,
                            AirportCode = "CLJ",
                            City = "Cluj-Napoca",
                            Name = "Cluj International"
                        },
                        new
                        {
                            Id = 4,
                            AirportCode = "CDG",
                            City = "Paris",
                            Name = "Charles de Gaulle"
                        },
                        new
                        {
                            Id = 5,
                            AirportCode = "DXB",
                            City = "Dubai",
                            Name = "Dubai International"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.BotMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Message_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Message_Text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("BotMessages");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cart_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartItem_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Chat_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Chat_Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = 0,
                            UserId = 101
                        },
                        new
                        {
                            Id = 2,
                            Status = 1,
                            UserId = 102
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Client_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alex Cooper"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Company_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 1,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 2,
                            Name = "Delta Airlines"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 3,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 4,
                            ManagerId = 2,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 1,
                            Name = "Emirates"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ticket_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Creation_Timestamp");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Description");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Subject");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("Urgency_Level");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Category_Name");

                    b.Property<int>("CategoryUrgencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("Default_Urgency_Level");

                    b.HasKey("Id");

                    b.ToTable("TicketCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Technical Support",
                            CategoryUrgencyLevel = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Billing",
                            CategoryUrgencyLevel = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "General Feedback",
                            CategoryUrgencyLevel = 0
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Subcategory_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoryExternalReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("External_Reference_Id");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Subcategory_Name");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("TicketSubcategories");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password_Hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Email = "customer1@gmail.com",
                            MembershipId = 1,
                            PasswordHash = "HASH123",
                            Username = "traveler_one"
                        },
                        new
                        {
                            Id = 102,
                            Email = "customer2@yahoo.com",
                            MembershipId = 2,
                            PasswordHash = "HASH456",
                            Username = "sky_high"
                        },
                        new
                        {
                            Id = 103,
                            Email = "customer3@outlook.com",
                            MembershipId = 3,
                            PasswordHash = "HASH789",
                            Username = "globe_trotter"
                        },
                        new
                        {
                            Id = 104,
                            Email = "customer4@gmail.com",
                            MembershipId = 4,
                            PasswordHash = "HASH000",
                            Username = "business_flyer"
                        },
                        new
                        {
                            Id = 105,
                            Email = "customer5@yahoo.com",
                            MembershipId = 1,
                            PasswordHash = "HASH111",
                            Username = "vacation_mode"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Employee_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("Date_of_Birth");

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date")
                        .HasColumnName("Hire_Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<int>("Salary")
                        .HasColumnType("int")
                        .HasColumnName("Salary");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateOnly(1985, 5, 12),
                            HiringDate = new DateOnly(2020, 1, 1),
                            Name = "Andrei Popescu",
                            Role = 1,
                            Salary = 12000
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateOnly(1995, 9, 20),
                            HiringDate = new DateOnly(2022, 6, 15),
                            Name = "Maria Ionescu",
                            Role = 3,
                            Salary = 7000
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateOnly(1988, 11, 3),
                            HiringDate = new DateOnly(2021, 3, 10),
                            Name = "Vlad Georgescu",
                            Role = 2,
                            Salary = 10000
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateOnly(1997, 2, 14),
                            HiringDate = new DateOnly(2023, 4, 5),
                            Name = "Elena Dumitrescu",
                            Role = 3,
                            Salary = 6800
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateOnly(1982, 8, 30),
                            HiringDate = new DateOnly(2015, 11, 1),
                            Name = "Cristian Matei",
                            Role = 1,
                            Salary = 13500
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateOnly(1990, 12, 25),
                            HiringDate = new DateOnly(2019, 2, 20),
                            Name = "Anca Stoica",
                            Role = 4,
                            Salary = 8500
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateOnly(1992, 4, 15),
                            HiringDate = new DateOnly(2022, 8, 1),
                            Name = "Mihai Enache",
                            Role = 2,
                            Salary = 9500
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateOnly(1994, 7, 10),
                            HiringDate = new DateOnly(2021, 5, 12),
                            Name = "Sonia Marinescu",
                            Role = 3,
                            Salary = 7200
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.EmployeeFlight", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("EmployeeFlights");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FAQ_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Answer_Text");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<int>("HelpfulVotesCount")
                        .HasColumnType("int")
                        .HasColumnName("Helpful_Votes");

                    b.Property<int>("NotHelpfulVotesCount")
                        .HasColumnType("int")
                        .HasColumnName("Not_Helpful_Votes");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Question_Text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("View_Count");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQNode", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeId"));

                    b.Property<bool>("IsFinalAnswer")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeId");

                    b.ToTable("FAQNodes", (string)null);

                    b.HasData(
                        new
                        {
                            NodeId = 1,
                            IsFinalAnswer = false,
                            QuestionText = "How can I help you?"
                        },
                        new
                        {
                            NodeId = 2,
                            IsFinalAnswer = false,
                            QuestionText = "What's wrong with your baggage?"
                        },
                        new
                        {
                            NodeId = 3,
                            IsFinalAnswer = true,
                            QuestionText = "Contact the Lost & Found desk at Level 1."
                        },
                        new
                        {
                            NodeId = 4,
                            IsFinalAnswer = true,
                            QuestionText = "You can change seats in the My Booking app."
                        },
                        new
                        {
                            NodeId = 5,
                            IsFinalAnswer = true,
                            QuestionText = "Please go to the baggage services desk or file a lost baggage report at the arrivals hall."
                        },
                        new
                        {
                            NodeId = 6,
                            IsFinalAnswer = true,
                            QuestionText = "Take photos and report the damage at the baggage service desk before leaving the airport."
                        },
                        new
                        {
                            NodeId = 7,
                            IsFinalAnswer = true,
                            QuestionText = "Use your reference number to track the bag and contact baggage services if it does not arrive."
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<int?>("BotMessageId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NextNodeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentNodeId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("BotMessageId");

                    b.HasIndex("NextNodeId");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("FAQOptions", (string)null);

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            Label = "Baggage Issues",
                            NextNodeId = 2,
                            ParentNodeId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            Label = "Seat Selection",
                            NextNodeId = 4,
                            ParentNodeId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            Label = "Lost baggage",
                            NextNodeId = 5,
                            ParentNodeId = 2
                        },
                        new
                        {
                            OptionId = 4,
                            Label = "Damaged baggage",
                            NextNodeId = 6,
                            ParentNodeId = 2
                        },
                        new
                        {
                            OptionId = 5,
                            Label = "Delayed baggage",
                            NextNodeId = 7,
                            ParentNodeId = 2
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Flight_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Departure_Date");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Flight_Number");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("RunwayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.HasIndex("RouteId");

                    b.HasIndex("RunwayId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 5, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "BA101",
                            GateId = 1,
                            RouteId = 1,
                            RunwayId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 5, 21, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "DL455",
                            GateId = 3,
                            RouteId = 2,
                            RunwayId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 5, 22, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "W6 3301",
                            GateId = 5,
                            RouteId = 3,
                            RunwayId = 3
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FlightTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ticket_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Passenger_Email");

                    b.Property<string>("PassengerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Passenger_First_Name");

                    b.Property<string>("PassengerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Passenger_Last_Name");

                    b.Property<string>("PassengerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Passenger_Phone");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("Price");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Seat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("FlightTickets");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Gate_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gate_Name");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Gates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportId = 1,
                            GateName = "A1"
                        },
                        new
                        {
                            Id = 2,
                            AirportId = 1,
                            GateName = "A2"
                        },
                        new
                        {
                            Id = 3,
                            AirportId = 2,
                            GateName = "B1"
                        },
                        new
                        {
                            Id = 4,
                            AirportId = 2,
                            GateName = "B2"
                        },
                        new
                        {
                            Id = 5,
                            AirportId = 3,
                            GateName = "C1"
                        },
                        new
                        {
                            Id = 6,
                            AirportId = 3,
                            GateName = "C2"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Manager_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "marcel@airport.com",
                            Name = "Marcel Ionescu",
                            Phone = "0745000001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "elena@airport.com",
                            Name = "Elena Vasilescu",
                            Phone = "0745000002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "victor@airport.com",
                            Name = "Victor Radu",
                            Phone = "0745000003"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Membership_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("FlightDiscountPercentage")
                        .HasColumnType("real")
                        .HasColumnName("Flight_Discount_Percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightDiscountPercentage = 0f,
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            FlightDiscountPercentage = 5f,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            FlightDiscountPercentage = 15f,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            FlightDiscountPercentage = 25f,
                            Name = "Platinum"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.MembershipAddonDiscount", b =>
                {
                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<int>("AddOnId")
                        .HasColumnType("int");

                    b.Property<float>("DiscountPercentage")
                        .HasColumnType("real")
                        .HasColumnName("Discount_Percentage");

                    b.HasKey("MembershipId", "AddOnId");

                    b.HasIndex("AddOnId");

                    b.ToTable("Membership_Addon_Discounts");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Message_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Message_Text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Reservation_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("ReservationCartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Reservation_Date");

                    b.HasKey("Id");

                    b.HasIndex("ReservationCartId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Review_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanlinessRating")
                        .HasColumnType("int")
                        .HasColumnName("Cleanliness_Rating");

                    b.Property<int>("DutyFreeRating")
                        .HasColumnType("int")
                        .HasColumnName("Duty_Free_Rating");

                    b.Property<int>("FlightExperienceRating")
                        .HasColumnType("int")
                        .HasColumnName("Flight_Experience_Rating");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Message");

                    b.Property<int>("StaffFriendlinessRating")
                        .HasColumnType("int")
                        .HasColumnName("Staff_Friendliness_Rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CleanlinessRating = 5,
                            DutyFreeRating = 5,
                            FlightExperienceRating = 4,
                            Message = "Great airport, very clean!",
                            StaffFriendlinessRating = 5,
                            UserId = 101
                        },
                        new
                        {
                            Id = 2,
                            CleanlinessRating = 4,
                            DutyFreeRating = 3,
                            FlightExperienceRating = 2,
                            Message = "Security took too long.",
                            StaffFriendlinessRating = 3,
                            UserId = 102
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Route_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time")
                        .HasColumnName("Arrival_Time");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time")
                        .HasColumnName("Departure_Time");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("Arrival_Date");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("int")
                        .HasColumnName("Recurrence_Interval");

                    b.Property<string>("RouteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Route_Type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("Departure_Date");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportId = 1,
                            ArrivalTime = new TimeOnly(11, 0, 0),
                            Capacity = 180,
                            CompanyId = 1,
                            DepartureTime = new TimeOnly(8, 0, 0),
                            EndDate = new DateOnly(2026, 12, 31),
                            RecurrenceInterval = 1,
                            RouteType = "DEP",
                            StartDate = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            AirportId = 2,
                            ArrivalTime = new TimeOnly(18, 30, 0),
                            Capacity = 220,
                            CompanyId = 2,
                            DepartureTime = new TimeOnly(14, 0, 0),
                            EndDate = new DateOnly(2026, 12, 31),
                            RecurrenceInterval = 1,
                            RouteType = "ARR",
                            StartDate = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            AirportId = 3,
                            ArrivalTime = new TimeOnly(9, 45, 0),
                            Capacity = 150,
                            CompanyId = 3,
                            DepartureTime = new TimeOnly(6, 30, 0),
                            EndDate = new DateOnly(2026, 12, 31),
                            RecurrenceInterval = 2,
                            RouteType = "DEP",
                            StartDate = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Runway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Runway_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HandleTime")
                        .HasColumnType("int")
                        .HasColumnName("Handle_Time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Runways");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HandleTime = 15,
                            Name = "R-09L"
                        },
                        new
                        {
                            Id = 2,
                            HandleTime = 12,
                            Name = "R-27R"
                        },
                        new
                        {
                            Id = 3,
                            HandleTime = 20,
                            Name = "R-18"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Sender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Sender_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Discriminator");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email_Address");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Full_Name");

                    b.HasKey("Id");

                    b.ToTable("Senders", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Sender");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Discriminator = "Bot",
                            EmailAddress = "customer-support@cloudspritzers.com",
                            FullName = "Carlos"
                        },
                        new
                        {
                            Id = -2,
                            Discriminator = "Administrator",
                            EmailAddress = "admin@airport.com",
                            FullName = "System Admin"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Shop_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 1,
                            Name = "Duty Free Global",
                            Type = "Retail"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 2,
                            Name = "Starbucks",
                            Type = "Coffee"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 3,
                            Name = "Book World",
                            Type = "Books"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShopItem_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Luxury scent",
                            Name = "Perfume",
                            Photo = "perfume.jpg",
                            Price = 85f,
                            Quantity = 50,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Single Malt",
                            Name = "Whiskey",
                            Photo = "whiskey.jpg",
                            Price = 45f,
                            Quantity = 30,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Grande size",
                            Name = "Caffe Latte",
                            Photo = "coffee.jpg",
                            Price = 5.5f,
                            Quantity = 200,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Memory foam",
                            Name = "Travel Pillow",
                            Photo = "pillow.jpg",
                            Price = 25f,
                            Quantity = 100,
                            ShopId = 3
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Administrator", b =>
                {
                    b.HasBaseType("AirportApp.ClassLibrary.Entity.Domain.Sender");

                    b.ToTable("Senders");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.User", b =>
                {
                    b.HasBaseType("AirportApp.ClassLibrary.Entity.Domain.Sender");

                    b.ToTable("Senders");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Discriminator = "User",
                            EmailAddress = "alice@travel.com",
                            FullName = "Alice Traveler"
                        },
                        new
                        {
                            Id = 102,
                            Discriminator = "User",
                            EmailAddress = "bob@voyage.com",
                            FullName = "Bob Voyager"
                        },
                        new
                        {
                            Id = 103,
                            Discriminator = "User",
                            EmailAddress = "mia@example.com",
                            FullName = "Mia Passenger"
                        });
                });

            modelBuilder.Entity("AddOnFlightTicket", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.AddOn", null)
                        .WithMany()
                        .HasForeignKey("SelectedAddOnsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.FlightTicket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.BotMessage", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Cart", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.CartItem", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Chat", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Company", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicket", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketSubcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketSubcategory", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketCategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Customer", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.EmployeeFlight", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQOption", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.BotMessage", null)
                        .WithMany("FAQOptions")
                        .HasForeignKey("BotMessageId");

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.FAQNode", "NextOption")
                        .WithMany()
                        .HasForeignKey("NextNodeId");

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.FAQNode", null)
                        .WithMany("Options")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NextOption");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Flight", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Runway", "Runway")
                        .WithMany()
                        .HasForeignKey("RunwayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gate");

                    b.Navigation("Route");

                    b.Navigation("Runway");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FlightTicket", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Customer", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Gate", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Airport", "Airport")
                        .WithMany("Gates")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.MembershipAddonDiscount", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.AddOn", "AddOn")
                        .WithMany()
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Membership", "Membership")
                        .WithMany("AddonDiscounts")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Message", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Reservation", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Cart", "ReservationCart")
                        .WithMany()
                        .HasForeignKey("ReservationCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationCart");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Review", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Route", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Shop", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ShopItem", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Airport", b =>
                {
                    b.Navigation("Gates");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.BotMessage", b =>
                {
                    b.Navigation("FAQOptions");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQNode", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Membership", b =>
                {
                    b.Navigation("AddonDiscounts");
                });
#pragma warning restore 612, 618
        }
    }
}
